### PR TITLE
#162: pom initial

### PR DESCRIPTION
**Pull request by includealex**
Refers to [#162](https://github.com/polystat/j2eo/issues/162).
After todo work file 'build.gradle.kts' should be deleted.

### CODE REVIEW

**Comment by includealex** [comment]
@yegor256 please check it.

**Comment by yegor256** [comment]
@includealex try to run `xcop` with your code: https://github.com/yegor256/xcop

**Comment by includealex** [comment]
@yegor256 please check it.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
