### PR TITLE
Stdlib updates: numeric conversions from any type to any type

### PR DESCRIPTION
**Pull request by someilay**
#### Stdlib updates::
* All classes fixed according to [#124](https://github.com/polystat/j2eo/issues/124)
* Added runtime support of numeric conversions from any type to any type

### CODE REVIEW

**Comment by someilay** [comment]
Stdlib: minor bugs fixed
Readme: work on chapter [4](https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html) continued

**Comment by someilay** [comment]
Readme: chapter [4](https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html) finished, chapter [5](https://docs.oracle.com/javase/specs/jls/se11/html/jls-5.html) started

**Comment by egorklementev** [comment]
@rultor, merge

**Comment by someilay** [comment]
#### New test for chapter [14](https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html)
Subsections [14.2](https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-14.2) and [14.3](https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-14.3) are extended

**Comment by egorklementev** [comment]
@rultor, merge

**Pull request merged**
